# Generated by Django 3.1 on 2021-04-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistepformmodel',
            name='ort',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepformmodel',
            name='plz',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
