# Generated by Django 3.1 on 2021-04-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularapp', '0003_auto_20210404_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multistepformmodel',
            name='gewerbe',
        ),
    ]
