# Generated by Django 3.1 on 2021-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularapp', '0004_remove_multistepformmodel_gewerbe'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistepformmodel',
            name='gewerbe',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
