# Generated by Django 3.1 on 2021-04-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularapp', '0005_multistepformmodel_gewerbe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multistepformmodel',
            name='gewerbe',
        ),
        migrations.RemoveField(
            model_name='multistepformmodel',
            name='privat',
        ),
    ]
