# Generated by Django 3.1 on 2021-04-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularapp', '0006_auto_20210404_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistepformmodel',
            name='auswahl',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
