# Generated by Django 3.1 on 2021-04-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularapp', '0007_multistepformmodel_auswahl'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistepformmodel',
            name='auswahl2',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepformmodel',
            name='auswahl3',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepformmodel',
            name='auswahl4',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepformmodel',
            name='auswahl5',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepformmodel',
            name='auswahl6',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepformmodel',
            name='auswahl7',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepformmodel',
            name='auswahl8',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
