# Generated by Django 3.1 on 2021-04-06 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularapp', '0008_auto_20210406_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='auswahl',
            new_name='gewerbeflaeche',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='auswahl2',
            new_name='grundversorger',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='auswahl3',
            new_name='oekotarif',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='auswahl4',
            new_name='personen_im_haushalt',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='auswahl5',
            new_name='privat_oder_gewerbe',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='auswahl6',
            new_name='rueckruftermin',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='auswahl7',
            new_name='strom_oder_gas',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='auswahl8',
            new_name='wohnflaeche',
        ),
    ]
